
services:
  db:
    image: mysql
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"


  redis:
    image: redis:alpine
    container_name: redis_test
    ports:
      - "6379:6379"

